In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
print(a)

[0 1 2 3 4 5]


In [11]:
print(a[2])

2


In [5]:
a.shape

(6,)

In [7]:
a1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [8]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a1.ndim

2

In [12]:
print(a1[1])

[4 5 6]


In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

<b>even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!</b>

In [19]:
np.empty(4)

array([0.00000000e+000, 5.49874242e-313, 8.79798787e-312, 3.62483311e+228])

In [20]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [22]:
np.linspace(1,15,10)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

<b>While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.</b>

In [23]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [25]:
arr = np.array([2,4,3,6,3,53,56,3,2,45,534,2])
np.sort(arr)

array([  2,   2,   2,   3,   3,   3,   4,   6,  45,  53,  56, 534])

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([4,5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [31]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
array = np.array([[[1,2,3],
                   [3,4,5],
                   [5,6,7]],
                  
                  [[0,1,2],
                   [4,5,6],
                   [1,2,3]],
                 
                  [[5,6,7],
                   [8,9,10],
                   [11,12,13]]])

In [33]:
array

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 5,  6,  7]],

       [[ 0,  1,  2],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]]])

In [34]:
array.ndim

3

In [35]:
array.size

27

In [37]:
array.shape

(3, 3, 3)

In [40]:
a = np.arange(6)
print(a)
b = a.reshape(3,2)
b

[0 1 2 3 4 5]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [42]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [43]:
a2 = a[:,np.newaxis]
a2.shape

(6, 1)

In [45]:
a2 = np.expand_dims(a,axis=1)
a2.shape

(6, 1)

In [54]:
a2 = np.expand_dims(a,axis=0)
a2.shape

(1, 6)

# Indexing and slicing

In [55]:
data = np.array([1, 2, 3])
data[1]

2

In [56]:
data[0:2]

array([1, 2])

In [57]:
data[:]

array([1, 2, 3])

In [58]:
data[1:]

array([2, 3])

In [59]:
data[:2]

array([1, 2])

In [63]:
data[-1]

3

In [64]:
data[-1:]

array([3])

In [65]:
data[:-1]

array([1, 2])

In [82]:
# a = np.array([1,4,3,6,2,7])
# for i in a:
#     for j in a:
#         if i+j==target:
#             print([i,j])
   

In [ ]:
for i in range(9)